import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Main from "./main";
import Script from "next/script";

export const metadata = {
  title: "Software House | Mobile App & Web Development Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name=" google-site-verification"
          content=" google06cf607652d5d6d8.html"
        />

        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="robots"
          content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large"
        />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <meta
          name="description"
          content="Atrule is top Software House in Pakistan providing diverse technologies like Web Development, Mobile App, &amp; Desktop App Development. No.1 Software House in Pakistan"
        />
        <meta
          name="robots"
          content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large"
        />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Software House | Mobile App &amp; Web Development Services"
        />
        <meta
          property="og:description"
          content="Atrule is top Software House in Pakistan providing diverse technologies like Web Development, Mobile App, &amp; Desktop App Development. No.1 Software House in Pakistan"
        />
        <meta property="og:url" content="https://atrule.com/" />
        <meta property="og:site_name" content="ATRULE Technologies (Pvt) Ltd" />
        <meta property="og:updated_time" content="2023-07-05T14:43:35+00:00" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content="Software House | Mobile App &amp; Web Development Services"
        />
        <meta
          name="twitter:description"
          content="Atrule is top Software House in Pakistan providing diverse technologies like Web Development, Mobile App, &amp; Desktop App Development. No.1 Software House in Pakistan"
        />
        <meta name="twitter:site" content="@Atruletech" />
        <meta name="twitter:creator" content="@Atruletech" />
        <meta name="twitter:label1" content="Written by" />
        <meta name="twitter:data1" content="Atrule Website Admin" />
        <meta name="twitter:label2" content="Time to read" />
        <meta name="twitter:data2" content="Less than a minute" />
        <meta name="redi-version" content="1.1.5" />
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />

        <link rel="preconnect" href="https://www.googletagmanager.com"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/assets/css/main.css" />
        <link rel="stylesheet" href="/assets/css/styles.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
        {/* <Script
          defer
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-WRXEWTG2DK"
        />
        <script
          type="application/ld+json"
          defer
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org/",
              "@type": "WebSite",
              name: "atrule technologies",
              url: "https://atrule.com/",
              potentialAction: {
                "@type": "SearchAction",
                target:
                  "https://your-website.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          defer
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org/",
              "@type": "WebSite",
              name: "Atrule Technologies",
              alternateName: "Atrule",
              url: "https://atrule.com/",
            }),
          }}
        /> */}

        {/* <script
          type="text/javascript"
          defer
          dangerouslySetInnerHTML={{
            __html: ` (function(w,d,s,l,i){
                  w[l]=w[l]||[];
                  w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
                  var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
                  j.async=true;
                  j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
                  f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-TVJK5DD')`,
          }}
        /> */}

        {/* <script
          type="text/javascript"
          defer
          // async
          dangerouslySetInnerHTML={{
            __html: ` window.dataLayer = window.dataLayer || [];
              function gtag() {
                dataLayer.push(arguments);
              }
              gtag('js', new Date());
              gtag('config', 'G-WRXEWTG2DK');`,
          }}
        /> */}
      </head>
      <body className={inter.className}>
        {/* <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TVJK5DD"
            height="0"
            width="0"
            style="display:none;visibility:hidden"
          ></iframe>
        </noscript> */}
        <div className="wrapper position-relative">
          <Main data={children} />
        </div>
        {/* <Script
          src="/assets/js/jquery.min.js"
          strategy="afterInteractive"
          type="text/javascript"
          defer
        /> */}
        {/* <script src="/assets/js/slick-carousel.js"></> */}
        <Script
          src="/assets/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
          defer
        />
        <Script
          src="/assets/js/popper.min.js"
          strategy="afterInteractive"
          defer
        />
        <Script
          type="module"
          src="/assets/js/modal.js"
          strategy="afterInteractive"
          defer
        />
        {/* <script src="/assets/js/main.js"></> */}
        {/* <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TVJK5DD" height="0" width="0" style="display: none; visibility: hidden;"></iframe>`,
          }}
        /> */}
      </body>
    </html>
  );
}
